apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-world
    type: backend
  name: hello-world-service
  namespace: prerna
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30008
  selector:
    app: hello-world
    type: backend
  type: NodePort
status:
  loadBalancer: {}
